version: '3.9'

services:

 php:
  container_name: php
  build: 
   context: .
   dockerfile: ./php/Dockerfile
  ports: [ '9000:9000' ]

 nginx:
  container_name: nginx
  image: nginx:stable-alpine
  ports: [ '80:80' ]
  volumes:
   - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  depends_on:
   - php

 mysql:
  image: 'mysql:8.0'
  container_name: mysql
  environment:
   MYSQL_ROOT_PASSWORD: advant
   MYSQL_DATABASE: advant
   MYSQL_USER: advant
   MYSQL_PASSWORD: advant
  ports: [ '3306:3306' ]
  volumes: [ 'mysql_data:/var/lib/mysql' ]

 myadmin:
  image: phpmyadmin/phpmyadmin
  container_name: phpmyadmin
  ports: [ '8080:80' ]
  environment:
   - PMA_ARBITRARY=1
   - PMA_HOST=mysql
  depends_on:
   - mysql

volumes:
 mysql_data:
